### ISSUE TITLE
[Damian] ISSUE #8: Press X too Many Times on Black Smith disabled camera

### ISSUE THREAD

**Issue by DamianAngelone** [NathanCoit/4GP6Capstone#71]
While attempting to press X on a black smith, I managed to disable the camera for a duration of time (longer disable for the larger amount of spams).

**Comment by NathanCoit** [comment]
X in intended to disable camera movement and bring up a panel for unlocking upgrades. Since the Blacksmith building was not implemented at the time, only a stub to disable camera movement was enabled. Pressing X disabled the camera and called a stub to show upgrade UI which didn't exist yet. Merging this issue into #122
